version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./nextcloud-database:/var/lib/postgresql/data:Z
    env_file:
      - db.env
    networks:
      - nextcloud-network

  redis:
    image: redis:alpine
    restart: always
    networks:
      - nextcloud-network

  cron:
    image: nextcloud
    restart: always
    volumes:
      - ./nextcloud-data:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - nextcloud-network

  app:
    image: nextcloud
    restart: always
    volumes:
      - ./nextcloud-data:/var/www/html:z
    ports:
      - 8080:80
    environment:
      - POSTGRES_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - nextcloud-network

  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    networks:
      - nextcloud-network
    depends_on:
      - app        

networks:
  nextcloud-network:
    driver: bridge
